function options_default = bayes_nca_default_options(A_prior_mean,B_prior_mean)

%options_default = bayes_nca_default_options(A_prior_mean,B_prior_mean)
%
%Options for Bayesian NCA
%
% options.method:           'posterior mode'; 'gibbs sampling'
% options.verbose           Print output?
% options.graphics_flag     Show graphics during optimisation?
% options.n_it_max          Number of iterations (default 10)
% options.n_accept          Number of iterations considered for posterior sampling 
% options.seed              Random seed
% options.epsilon
% options.lambda
% options.repeat
% options.nan_Y_mean
% options.nan_A_prior_mean
% options.nan_B_prior_mean
% options.nan_Y_std
% options.nan_A_prior_std
% options.nan_B_prior_std
% options.A_init
% options.B_init
% options.A_max_abs
% options.A_min_abs

options_default = struct(...
    'method','posterior mode',...
    'n_it_max', 10, ...
    'seed', nan, ...
    'lambda', 1, ...
    'repeat', 1, ...
    'epsilon', 0.001, ...
    'n_accept', 1, ...
    'A_first', A_prior_mean, ...
    'B_first', B_prior_mean, ...
    'A_max_abs', 100, ...
    'A_min_abs', 0,  ...
    'nan_Y_mean', 0, ...
    'nan_Y_std', 10, ...
    'nan_A_prior_mean', 0, ...
    'nan_A_prior_std', 10, ...
    'nan_B_prior_mean', 0, ...
    'nan_B_prior_std', 10, ...
    'verbose', 0, ...
    'graphics_flag', 0);
